# Generated by Django 3.2.7 on 2021-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
